### ISSUE TITLE
Events when a tour has been completed

### ISSUE THREAD

**Issue by Reached** [pulsardev/vue-tour#14] opened 2018-04-04 13:04 UTC
Would be great if an event was fired once the tour was completed or dismissed :)

**Comment by mmorainville** [comment] 2018-04-04 13:59
Hi @Reached,

It could be a good idea. For now you can use custom callbacks though, it's not documented yet but it's implemented already and events could be seen as a duplicate of this feature so I'm not sure it would really be useful.

If you want to trigger an action when the tour is completed or dismissed for now you can do:

```html
<v-tour name="myTour" :steps="steps" :callbacks="myCallbacks"></v-tour>
```

```js
data () {
  return {
    myCallbacks: {
      onStop: function () {
        // Do whatever you want
      }
    }
  }
}
```

**Comment by Reached** [comment] 2018-04-04 14:38
That is awesome! I definitely agree that since you have these callbacks, you dont really need events, even though I think events make more sense in terms of naming :)

Good job!

**Comment by Reached** [comment] 2018-04-05 08:57
While it works (the callbacks are triggered),  the ```this``` context is now messed up. Do you know how I can access the vue component (this) inside of the callback?

Thanks!

**Comment by mmorainville** [comment] 2018-04-05 09:06
Hi @Reached,

Then do this:

```js
data () {
  return {
    myCallbacks: {
      onStop: this.onStop
    }
  }
},
methods: {
  onStop () {
    // Do whatever you want
  }
}
```

**Comment by Reached** [comment] 2018-04-05 10:01
Yes of course! Thanks :)

**Closed** 2018-04-05 20:30 UTC
Labels: invalid

**Comment by maxiride** [comment] 2021-01-12 14:58
I was searching for the same event\callback and stumbled here. Just want to report that the `onStop` callback is undocumented here https://github.com/pulsardev/vue-tour/wiki/Callbacks is it deprecated and available for legacy compatibily or it was missing simply for a distraction? =)

**Comment by gca-bliss** [comment] 2021-07-27 22:10
came here to do the same @maxiride did. onStop is not documented, but it seems to work. albeit it still triggers even if there's no tour running

**Comment by DrJfrost** [comment] 2021-08-24 21:54
came here to tell the same onStop callback is not documented =)

**Comment by simar7** [comment] 2022-08-03 23:46
came here to say the same :)
