### ISSUE TITLE
in IE11，click 图和

### ISSUE THREAD

**Issue by goSunadeod** [pulsardev/vue-tour#56] opened 2018-12-07 16:32 UTC

**Comment by goSunadeod** [comment] 2018-12-07 16:34
like the title

**Comment by Outpox** [comment] 2018-12-07 17:09
Hey there @goSunadeod !
I'm sorry but we don't speak chinese and we'll need a description of your issue. Right now we can't be of any help.

**Comment by goSunadeod** [comment] 2018-12-07 17:15
i am so sorry, The problem is under ie11，when I click the next button,the browser will flash and there will be a flashing scroll bar, in chrome is no this problem

**Comment by goSunadeod** [comment] 2018-12-07 17:29
after i see you code , i find  `this.params.enableScrolling` ,so i add this  attribute  FALSE to solve my problem temporarily，thank you

**Comment by Outpox** [comment] 2018-12-07 17:33
Glad you found a way to fix your issue.  
I've just tried in IE11 [on the showcase](https://pulsardev.github.io/vue-tour/) and couldn't reproduce your issue, could you try it as well and report back?

**Comment by goSunadeod** [comment] 2018-12-07 17:59
It's two o 'clock in the morning in China，so I'll take a closer look at validation when I have time to make sure it's not a problem with my own code

**Comment by Outpox** [comment] 2018-12-07 18:41
Alright 👍

**Comment by goSunadeod** [comment] 2018-12-10 02:59
Sorry to have kept you waiting，I reproduced the problem， [on the showcase](https://pulsardev.github.io/vue-tour/) really is no blinking problem，because a scroll bar appears on the screen，if when initialized, the page does not have a scroll bar and  will have the flicker problem that I described

**Comment by Outpox** [comment] 2018-12-10 08:13
No problem ;-)
I understand the issue and will try to reproduce it.
@mmorainville could you look into this as well?

**Comment by mmorainville** [comment] 2019-05-23 12:24
Maybe a gif or webm of the problem could help because it seems we can't reproduce the problem. I'm closing this issue for now.

**Closed by mmorainville** 2019-05-23 12:24 UTC
Labels: wontfix
