### ISSUE TITLE
z-index option with a backdrop

### ISSUE THREAD

**Issue by darkscript** [pulsardev/vue-tour#10] opened 2018-03-28 05:49 UTC
It would be a great improvement to have the backdrop option, if the tour is on, we hide the rest of the page with a shadow and also add a big z-index so that the tour will always be on top of everything. My idea is inspired by https://gilbarbara.github.io/react-joyride/ (react based tour)

**Comment by mmorainville** [comment] 2018-03-28 09:16
Hi @darkscript,

I'm closing this issue since it's kind of a duplicate of the other one you opened just after (https://github.com/pulsardev/vue-tour/issues/11).

**Closed** 2018-03-28 09:16 UTC
Labels: duplicate
