### ISSUE TITLE
README Installation guide is not working in Laravel6 webpack

### ISSUE THREAD

**Issue by tomohirohiratsuka** [pulsardev/vue-tour#163] opened 2021-01-04 17:04 UTC
Hi, I followed installation guide on readme document, but it was not working.
I got below errors.
```
Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.use (app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:279576)
    at Module../resources/js/app.js (app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:332299)
    at __webpack_require__ (app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:20)
    at Object.0 (app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:380879)
    at __webpack_require__ (app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:20)
    at app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:84
    at app.js?__WB_REVISION__=da01a1e15a2820b468ba0b33148bcc02:87
```
I though this installation error happened because `index.d.ts` does not have `export default`, so I tried installation from `"vue-tour/src/main"` instead then it was working.

Is this expected behavior or not ? I'd appreciate if you tell correct installation way. Thank you.

Below code is what i use now.
app.js
```
import Vue from 'vue'
import App from '$layouts/App' // same as App.vue
import VueTour from "vue-tour/src/main";
require('vue-tour/dist/vue-tour.css')
Vue.use(VueTour)

export const app = new Vue({
  render: h => h(App)
}).$mount('#app')
```

**Comment by mmorainville** [comment] 2021-03-27 01:40
Hi @tomohirohiratsuka,

It should work ok with "vue-tour". It's weird but the issue is mainly with your Laravel setup, not with vue-tour itself, so I'm closing this for now. Feel free to reopen with more information if needed.

**Closed by mmorainville** 2021-03-27 01:40 UTC
