### ISSUE TITLE
Doesn't correctly work with navigation draw from vuetify

### ISSUE THREAD

**Issue by noahsilverman** [pulsardev/vue-tour#96] opened 2019-12-05 07:51 UTC
I've setup a very basic site with a navigation drawer ,and some tabs inside that drawer.  Vue-tour fails to correctly position the popper window for any element referenced in the navigation drawer.  I am able to correctly find the referenced object using document.querySelector.

**Comment by szhorvath** [comment] 2019-12-11 12:37
I can confirm. Positioning doesn't work with vuetify.

**Comment by HZooly** [comment] 2019-12-11 14:01
Hi @noahsilverman, @szhorvath, thanks for this issue.
Are you able to provide a reproductible example of the problem?

**Comment by noahsilverman** [comment] 2019-12-15 03:50
Here is an App.vue file that illustrates the issue.  I tried setting ID tags for three different locations in the navbar.  None of them are working correctly.  

https://pastebin.com/8fvZaekQ

Depending on your screen size, you may need to close the navbar to seven see the tour popups.

**Comment by eyalfishler** [comment] 2020-01-24 06:37
Any update on this one? 
Having the same issue.

**Comment by noahsilverman** [comment] 2020-01-24 11:15
Nothing ever happened with this.  No reply from anyone

**Comment by szhorvath** [comment] 2020-01-24 14:32
@noahsilverman @eyalfishler I found an alternative that works with vuetify. [https://sschandi.github.io/vue-page-guide/guide/](https://sschandi.github.io/vue-page-guide/guide/)

**Comment by eyalfishler** [comment] 2020-01-27 21:22
@noahsilverman @szhorvath i updated vue-tour to work with a new build of popper js, 
still working on the params object, but i can confirm that everything seems to be working now.
you can test 
`npm install --save git+https://git@github.com:eyalfishler/vue-tour.git`
once i complete all changes and tests i will issue a PR

**Comment by mmorainville** [comment] 2020-01-28 14:53
Hi,

Sorry for the delay, we don't use Vuetify very often and were busy on other features so we didn't take time to check this.
@eyalfishler if you manage to get this to work, a PR is very welcome!!
We are in the process of merging all current open PRs right now, so it could be delivered quite quickly.

**Comment by eyalfishler** [comment] 2020-01-28 20:43
@mmorainville im having issues with the this.params object passed to createPopper, beside that it works as it should with vuetify (flex)

` 
import { createPopper } from '@popperjs/core'
.
.
.
/* new Popper(
          this.targetElement,
          this.$refs['v-step-' + this.hash],
          this.params
        ) */
        console.log('createPopper params', this.params)
        createPopper(
          this.targetElement,
          this.$refs['v-step-' + this.hash]
          // this.params
        )`

**Comment by PriimeTime** [comment] 2020-02-13 14:54
Any update on this? It's crucial.

**Comment by chamerling** [comment] 2020-04-20 14:10
Hello all,

Any update on this?

Thanks a lot

**Comment by HZooly** [comment] 2020-04-20 15:57
> Here is an App.vue file that illustrates the issue. I tried setting ID tags for three different locations in the navbar. None of them are working correctly.
> https://pastebin.com/8fvZaekQ

I've been able to reproduce example with your pastebin.
I think the main error in your code is that you don't provide the right selector. We use `document.querySelector` in Vue Tour for getting elements. If you want to target elements with ID, you need to prefix with `#`.

In your example, targets are `target: "#tour-test0"`.

**Comment by HZooly** [comment] 2020-04-20 15:58
@PriimeTime @chamerling are you please able to provide a reproductible example of the bug?
Given that it seems to be crucial for several people, we will try to give a check as soon as possible to this issue.

**Comment by chamerling** [comment] 2020-04-20 16:04
@HZooly I will send you something tomorrow. Thanks a lot

**Comment by chamerling** [comment] 2020-04-21 16:49
@HZooly I finally have it working with vuetify2. Also, I used some native vuetify2 components to create my own tour plugin since I needed to stay aligned with vuetify UI.

**Comment by HZooly** [comment] 2020-04-21 17:32
So can you figure out the origin of the problem?

**Comment by garyo** [comment] 2020-12-04 23:14
I need this too. Using vue 2 + vuetify. Positioning mostly works, except in my top nav bar, where the tour steps are too low.
I tried @eyalfishler 's fork based on popper2; it works better, positioning is correct, but the arrow elements don't show up (they show up as little dark rectangles). @eyalfishler did you ever make any further progress on this? Any chance it could get merged & fixed?

**Comment by souek88** [comment] 2021-01-08 20:43
@garyo  Try changing boundariesElement to 'window' in step params like this:


```
params: {
    enableScrolling: false,
    modifiers: {
        preventOverflow: {
            enabled: true,
            boundariesElement: 'window',
         }
     }
}


```

**Comment by akbarism** [comment] 2021-02-03 04:13
Any update on this?

**Comment by garyo** [comment] 2021-02-03 11:34
I switched to shepherd.js, which is based on a newer version of popper.js. Works fine, and I like that it doesn't need to be a separate Vue component.

**Comment by HZooly** [comment] 2021-03-28 11:55
A new version of Vue Tour has been deployed, can you try to update and see if you still got this issue?

**Comment by mmorainville** [comment] 2021-11-16 08:38
Closing as it should be solved by the Popper update in v2.x.

**Closed by mmorainville** 2021-11-16 08:38 UTC
Labels: bug, help wanted
