### ISSUE TITLE
Vue Tour is not properly working on Safari

### ISSUE THREAD

**Issue by Djshn** [pulsardev/vue-tour#119] opened 2020-03-30 19:11 UTC
I have a basic implementation of Vue-Tour that works fine on Chrome but it resizes the starting element (v-card) on Safari. I am also using Vuetify. Is this a bug?

**Comment by HZooly** [comment] 2020-04-17 10:04
Hi @Djshn, can you please provide an example ? I'm unable to reproduce the bug on Safari, everything is working well on my side.

**Comment by HZooly** [comment] 2020-05-21 23:24
@Djshn any news on this? Or I can close the issue?

**Closed** 2020-06-23 22:23 UTC
